name = "no_interaction"
stan_file = "src/stan/model.stan"
data_dir = "data/prepared/no_interaction"
modes = ["prior", "posterior", "cross_validation"]

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 2000
iter_sampling = 2000

[sample_kwargs.cross_validation]
chains = 1