name = "replicate_model"
stan_file = "src/stan/od-cdw-calibration_dilu-based.stan"
data_dir = "data/prepared/replicate_model"
modes = ["posterior"]

[stanc_options]
warn-pedantic = true

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 2000
iter_sampling = 2000

#[sample_kwargs.cross_validation]
#chains = 1